start color A0 
start color A1 
start color A2 
start color A3 
start color A4 
start color A5 
start color A6 
start color A7 
start color A8 
start color A9 
start color B0 
start color B1 
start color B2 
start color B3 
start color B4 
start color B5 
start color B6 
start color B7 
start color B8 
start color B9 
start color C0 
start color C1 
start color C2 
start color C3 
start color C4 
start color C5 
start color C6 
start color C7 
start color C8 
start color C9 
start color D0 
start color D1 
start color D2 
start color D3 
start color D4 
start color D5 
start color D6 
start color D7 
start color D8 
start color D9 
start color E0 
start color E1 
start color E2 
start color E3 
start color E4 
start color E5 
start color E6 
start color E7 
start color E8 
start color E9 
start color F0 
start color F1 
start color F2 
start color F3 
start color F4 
start color F5 
start color F6 
start color F7 
start color F8 
start color F9 
